server:
  port: 8096

spring:
  application:
    name: msvc-store
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/store-db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.agrocontrol.msvc_store.shared.infrastructure.persistence.jpa.SnakeCasePhysicalNamingStrategy
    open-in-view: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

documentation:
  application:
    description: "@project.description@"
    version: "@project.version@"

authorization:
  jwt:
    secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
    expiration:
      days: 7

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

resilience4j:
  circuitbreaker:
    instances:
      profile-store-cb:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 7s
  timelimiter:
    instances:
      profile-store-tl:
        timeoutDuration: 7s
        cancelRunningFuture: true
