server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  # Quitar la sección cloud.gateway.routes

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka